version: '3.6'
services:
    jmeter:
        hostname: jmeter
        image: jmeter:latest
        deploy:
           replicas: 1
        configs:
            - source: jmeter-scenario
              target: /var/jmeter/test.jmx
            - source: jmeter-log
              target: /usr/share/apache-jmeter/bin/log4j2.xml
        environment:
                TYPE: "WORKER"
                AWS_ACCESS_KEY_ID: "[]" 
                AWS_SECRET_ACCESS_KEY: "[]"
                AWS_DEFAULT_REGION: "us-east-1"
                BUCKET_NAME: "[]"
        networks:
        - net
networks:
  net:
configs:
  jmeter-scenario:
    file: my_script.jmx
    name: jmeter-jmx-file
  jmeter-log:
    file: log4j2.xml
    name: jmeter-log-file